### ISSUE TITLE
Clone URL is not a valid remote

### ISSUE THREAD

**Issue by saeideh94** [dergachev/redmine_git_remote#21]
Hi
i have two server :
1. redmine (OS:Centos7)
2. gitlab (OS:Centos7)

when i want create new repository in redmine's project , show below error :
Clone URL git@gitlabs:admin/myproject.git is not a valid remote.

i use ssh keygen :
when git clone by command in redmine server , show below error : 

sh: git-upload-pack: command not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

please help me for my problem

**Comment by dergachev** [comment]
Hi @saeideh94 thanks for trying the repo!

If you're having trouble running a `git clone` manually, I guess the problem isn't related to `redmine_git_remote`. Instead, it seems that the issue is in how you configured your `gitlabs` server. Googling that error suggests several possible workaround, mostly related to setting the $PATH properly for the `git` user.

http://serverfault.com/questions/176382/gitolite-setup-on-mac-git-upload-pack-command-not-found
http://stackoverflow.com/questions/11128464/git-upload-pack-command-not-found

Or it could be something else. Good luck!
